services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.jsgsoftwares.com
      - N8N_EDITOR_URL=https://n8n.jsgsoftwares.com
      - GENERIC_TIMEZONE=America/Panama
      - N8N_ENCRYPTION_KEY=streamvision-n8n-encryption-2026
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-automations.rule=Host(`n8n.jsgsoftwares.com`)"
      - "traefik.http.routers.n8n-automations.entrypoints=websecure"
      - "traefik.http.routers.n8n-automations.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n-automations.loadbalancer.server.port=5678"
    networks:
      - dokploy-network

volumes:
  n8n_data:

networks:
  dokploy-network:
    external: true